sudo: required

language: python

dist: xenial
services:
  - docker
  - xvfb

before_install:
  - docker build --build-arg PARALLEL_BUILDS=8 --build-arg TRAVIS=${TRAVIS} --tag test-xfce-ubuntu:latest --file dockerfiles/Dockerfile-devel .

script:
  - "./travis.sh"

